-- ============================================================================
-- DITY FLOW MASTER ARCHITECTURE & SEED DATA (ULTIMATE ALL ROUTES)
-- Mengakomodasi DANA deducted fee, Flip kode unik, dan fungsi All-Routes
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CLEAN UP
-- ----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.find_cheapest_route(varchar, varchar, numeric);
DROP FUNCTION IF EXISTS public.find_cheapest_route(varchar, varchar, numeric, int);
DROP FUNCTION IF EXISTS public.find_all_routes(varchar, varchar, numeric, int);

DROP TABLE IF EXISTS transfer_rules CASCADE;
DROP TABLE IF EXISTS institution_limits CASCADE;
DROP TABLE IF EXISTS institutions CASCADE;
DROP TYPE IF EXISTS fee_deduction_enum CASCADE;

-- ----------------------------------------------------------------------------
-- 2. SCHEMA CREATION
-- ----------------------------------------------------------------------------
CREATE TYPE fee_deduction_enum AS ENUM ('ADDED_TO_SOURCE', 'DEDUCTED_FROM_TARGET');

CREATE TABLE institutions (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    type VARCHAR NOT NULL, 
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE institution_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id VARCHAR NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    limit_type VARCHAR NOT NULL,
    max_value DECIMAL(12,2) NOT NULL,
    notes TEXT
);

CREATE TABLE transfer_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    destination_id VARCHAR NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
    fee_value DECIMAL(12, 2) NOT NULL,          
    fallback_fee DECIMAL(12, 2) DEFAULT NULL,   
    min_amount DECIMAL(12, 2) DEFAULT 10000.00,
    max_amount DECIMAL(12, 2) DEFAULT 50000000.00,
    free_quota INT DEFAULT 0,
    fee_deduction_type fee_deduction_enum DEFAULT 'ADDED_TO_SOURCE'::fee_deduction_enum NOT NULL,
    notes TEXT
);

-- ----------------------------------------------------------------------------
-- 3. SEED DATA: INSTITUSI
-- ----------------------------------------------------------------------------
INSERT INTO institutions (id, name, type) VALUES
('BCA', 'Bank Central Asia (BCA)', 'BANK'),
('BNI', 'Bank Negara Indonesia (BNI)', 'BANK'),
('BRI', 'Bank Rakyat Indonesia (BRI)', 'BANK'),
('MANDIRI', 'Bank Mandiri', 'BANK'),
('CIMB', 'CIMB Niaga', 'BANK'),
('SEABANK', 'SeaBank Indonesia', 'BANK'),
('JAGO', 'Bank Jago', 'BANK'),
('ALLO', 'Allo Bank', 'BANK'),
('DANA', 'DANA', 'E_WALLET'),
('GOPAY', 'GoPay', 'E_WALLET'),
('OVO', 'OVO', 'E_WALLET'),
('SHOPEEPAY', 'ShopeePay', 'E_WALLET'),
('LINKAJA', 'LinkAja', 'E_WALLET'),
('FLIP', 'Flip (Perantara)', 'APP_PERANTARA');

-- ----------------------------------------------------------------------------
-- 4. SEED DATA: ATURAN RUTE (SESUAI KONDISI TERKINI & KOREKSI)
-- ----------------------------------------------------------------------------
INSERT INTO transfer_rules (source_id, destination_id, fee_value, fallback_fee, free_quota, fee_deduction_type, min_amount, max_amount, notes) VALUES

-- A. BI-FAST (Rp 2.500 Semua Bank)
('BCA', 'BNI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BCA', 'BRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BCA', 'MANDIRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BCA', 'JAGO', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BCA', 'SEABANK', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),

('MANDIRI', 'BCA', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('MANDIRI', 'BNI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('MANDIRI', 'BRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('MANDIRI', 'JAGO', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('MANDIRI', 'SEABANK', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),

('BNI', 'BCA', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BNI', 'MANDIRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BNI', 'BRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BNI', 'JAGO', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BNI', 'SEABANK', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),

('BRI', 'BCA', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BRI', 'MANDIRI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BRI', 'BNI', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BRI', 'JAGO', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),
('BRI', 'SEABANK', 2500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 250000000, 'Transfer via BI-FAST'),

-- B. E-WALLET TOP-UP (KOREKSI REALITA - DIPOTONG DARI TARGET)
('BCA', 'GOPAY', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 10000000, 'Top Up via VA BCA'),
('BCA', 'SHOPEEPAY', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up via VA BCA (Biaya dipotong dari saldo masuk)'),
('BCA', 'DANA', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up DANA via VA BCA (Biaya dipotong dari saldo masuk)'),
('BCA', 'OVO', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up OVO via VA BCA (Biaya dipotong dari saldo masuk)'),

('MANDIRI', 'GOPAY', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 10000000, 'Top Up via Livin'),
('MANDIRI', 'SHOPEEPAY', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up via Livin (Biaya dipotong dari saldo masuk)'),
('MANDIRI', 'DANA', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up DANA via Livin (Biaya dipotong dari saldo masuk)'),
('MANDIRI', 'OVO', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up OVO via Livin (Biaya dipotong dari saldo masuk)'),

('BNI', 'GOPAY', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 10000000, 'Top Up via BNI Mobile'),
('BNI', 'SHOPEEPAY', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up via BNI (Biaya dipotong dari saldo masuk)'),
('BNI', 'DANA', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up DANA via BNI (Biaya dipotong dari saldo masuk)'),
('BNI', 'OVO', 1000.00, NULL, 0, 'DEDUCTED_FROM_TARGET', 10000, 10000000, 'Top Up OVO via BNI (Biaya dipotong dari saldo masuk)'),

-- C. INTEGRASI TIKUS EMAS (100% GRATIS)
('JAGO', 'GOPAY', 0.00, NULL, 999, 'ADDED_TO_SOURCE', 10000, 50000000, 'Integrasi Kantong Jago & GoPay'),
('GOPAY', 'JAGO', 0.00, NULL, 999, 'ADDED_TO_SOURCE', 10000, 50000000, 'Integrasi Kantong Jago & GoPay'),
('SHOPEEPAY', 'SEABANK', 0.00, NULL, 999, 'ADDED_TO_SOURCE', 10000, 20000000, 'Tarik saldo instan ke SeaBank'),
('SEABANK', 'SHOPEEPAY', 0.00, NULL, 999, 'ADDED_TO_SOURCE', 10000, 20000000, 'Top up instan dari SeaBank'),
('GOPAY', 'SEABANK', 0.00, NULL, 999, 'ADDED_TO_SOURCE', 10000, 20000000, 'Transfer Virtual Account gratis via GoPay'),

-- D. DANA WITHDRAWAL (KOREKSI REALITA Rp4.500)
-- DANA >= Rp50.000 (Ada kuota gratis, fallback Rp4.500)
('DANA', 'BCA', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
('DANA', 'MANDIRI', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
('DANA', 'BNI', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
('DANA', 'BRI', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
('DANA', 'JAGO', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
('DANA', 'SEABANK', 0.00, 4500.00, 10, 'ADDED_TO_SOURCE', 50000.00, 10000000, 'Tarik saldo DANA (Gratis kuota bulanan)'),
-- DANA < Rp50.000 (Selalu kena tarif dasar Rp4.500)
('DANA', 'BCA', 4500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000.00, 49999.99, 'Tarik saldo DANA nominal kecil'),
('DANA', 'MANDIRI', 4500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000.00, 49999.99, 'Tarik saldo DANA nominal kecil'),
('DANA', 'BNI', 4500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000.00, 49999.99, 'Tarik saldo DANA nominal kecil'),
('DANA', 'BRI', 4500.00, NULL, 0, 'ADDED_TO_SOURCE', 10000.00, 49999.99, 'Tarik saldo DANA nominal kecil'),

-- E. SEABANK & JAGO & GOPAY WITHDRAWALS
('SEABANK', 'BCA', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis Kuota SeaBank'),
('SEABANK', 'MANDIRI', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis Kuota SeaBank'),
('SEABANK', 'BNI', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis Kuota SeaBank'),
('SEABANK', 'DANA', 0.00, 1000.00, 100, 'ADDED_TO_SOURCE', 10000, 20000000, 'Gratis Kuota SeaBank (Topup DANA)'),

('JAGO', 'BCA', 0.00, 2500.00, 20, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis Kuota Bank Jago'),
('JAGO', 'MANDIRI', 0.00, 2500.00, 20, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis Kuota Bank Jago'),
('JAGO', 'DANA', 0.00, 1000.00, 20, 'ADDED_TO_SOURCE', 10000, 10000000, 'Gratis Kuota Bank Jago (Topup DANA)'),

('GOPAY', 'BCA', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis transfer aplikasi GoPay'),
('GOPAY', 'MANDIRI', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis transfer aplikasi GoPay'),
('GOPAY', 'BNI', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis transfer aplikasi GoPay'),
('GOPAY', 'BRI', 0.00, 2500.00, 100, 'ADDED_TO_SOURCE', 10000, 50000000, 'Gratis transfer aplikasi GoPay'),

-- F. FLIP SUPER HUB (KOREKSI REALITA KODE UNIK & TARIF E-WALLET)
-- Transfer MASUK ke Flip (Membutuhkan Kode Unik)
('BCA', 'FLIP', 0.00, NULL, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer VA/Rekening Flip (Wajib pakai Kode Unik di nominal)'),
('MANDIRI', 'FLIP', 0.00, NULL, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer VA/Rekening Flip (Wajib pakai Kode Unik di nominal)'),
('BNI', 'FLIP', 0.00, NULL, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer VA/Rekening Flip (Wajib pakai Kode Unik di nominal)'),
('BRI', 'FLIP', 0.00, NULL, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer VA/Rekening Flip (Wajib pakai Kode Unik di nominal)'),

-- Transfer KELUAR dari Flip -> Bank 
('FLIP', 'BCA', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'MANDIRI', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'BNI', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'BRI', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'CIMB', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'SEABANK', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),
('FLIP', 'JAGO', 0.00, 2500.00, 10, 'ADDED_TO_SOURCE', 10000, 5000000, 'Transfer Bank via Flip Gratis'),

-- Transfer KELUAR dari Flip -> E-Wallet (Koreksi Rp1.000)
('FLIP', 'GOPAY', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 5000000, 'Top Up GoPay via Flip (Ada biaya layanan)'),
('FLIP', 'DANA', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 5000000, 'Top Up DANA via Flip (Ada biaya layanan)'),
('FLIP', 'OVO', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 5000000, 'Top Up OVO via Flip (Ada biaya layanan)'),
('FLIP', 'SHOPEEPAY', 1000.00, NULL, 0, 'ADDED_TO_SOURCE', 10000, 5000000, 'Top Up ShopeePay via Flip (Ada biaya layanan)');


-- ----------------------------------------------------------------------------
-- 5. THE ENGINE: FUNGSI RPC FIND_ALL_ROUTES (MENGEMBALIKAN SEMUA ALUR)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.find_all_routes(
  p_source VARCHAR,
  p_destination VARCHAR,
  p_amount DECIMAL,
  p_bypass_quota INT DEFAULT 0
)
RETURNS TABLE (
  route_id INT,             
  step_number INT,
  from_institution VARCHAR,
  to_institution VARCHAR,
  fee_cost DECIMAL(12, 2),
  deduction_type VARCHAR,
  step_notes TEXT,
  total_route_fee DECIMAL(12, 2)
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS \$\$
BEGIN
  RETURN QUERY
  WITH RECURSIVE transfer_graph AS (
    -- TAHAP 1: Node Asal
    SELECT 
      1 as lvl,
      r.source_id,
      r.destination_id,
      CASE 
        WHEN p_bypass_quota = 1 AND r.fallback_fee IS NOT NULL THEN r.fallback_fee
        ELSE r.fee_value 
      END as total_fee,
      ARRAY[r.id] as edge_path,
      ARRAY[r.source_id::TEXT, r.destination_id::TEXT] as node_path
    FROM transfer_rules r
    WHERE r.source_id = p_source
      AND p_amount >= r.min_amount 
      AND p_amount <= r.max_amount

    UNION ALL

    -- TAHAP 2: Lompatan Rekursif (Maks 4 untuk kestabilan)
    SELECT 
      g.lvl + 1,
      r.source_id,
      r.destination_id,
      (g.total_fee + CASE 
        WHEN p_bypass_quota = 1 AND r.fallback_fee IS NOT NULL THEN r.fallback_fee
        ELSE r.fee_value 
      END) as total_fee,
      g.edge_path || r.id,
      g.node_path || r.destination_id::TEXT
    FROM transfer_graph g
    JOIN transfer_rules r ON g.destination_id = r.source_id
    WHERE NOT (r.destination_id::TEXT = ANY(g.node_path)) 
      AND p_amount >= r.min_amount 
      AND p_amount <= r.max_amount
      AND g.lvl < 4 
  ),
  ranked_paths AS (
    -- FILTER: Urutkan SEMUA rute yang berhasil mencapai tujuan, dari termurah ke termahal
    SELECT 
      g.total_fee,
      g.edge_path,
      DENSE_RANK() OVER (ORDER BY g.total_fee ASC, g.lvl ASC) as rn 
    FROM transfer_graph g
    WHERE g.destination_id = p_destination
  )
  -- KELUARAN PENGGABUNGAN: Kembalikan SEMUA rute tanpa limitasi "WHERE rp.rn <= 3"
  SELECT 
    (rp.rn)::INT as route_id,
    (p.idx)::INT as step_number,
    t.source_id::VARCHAR as from_institution,
    t.destination_id::VARCHAR as to_institution,
    (CASE 
      WHEN p_bypass_quota = 1 AND t.fallback_fee IS NOT NULL THEN t.fallback_fee
      ELSE t.fee_value 
    END)::DECIMAL(12,2) as fee_cost,
    t.fee_deduction_type::VARCHAR as deduction_type,
    (CASE 
      WHEN p_bypass_quota = 1 AND t.fallback_fee IS NOT NULL THEN 'Limit gratis terlewati! Biaya dialihkan ke tarif reguler.'::TEXT
      ELSE t.notes 
    END)::TEXT as step_notes,
    (rp.total_fee)::DECIMAL(12,2) as total_route_fee
  FROM ranked_paths rp
  CROSS JOIN LATERAL unnest(rp.edge_path) WITH ORDINALITY AS p(rule_id, idx)
  JOIN transfer_rules t ON t.id = p.rule_id
  ORDER BY rp.rn ASC, p.idx ASC;
END;
\$\$;
